language: node_js
node_js:
- '6.0'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp test
- gulp
deploy:
  provider: npm
  email: me@brianneisler.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: FlomiV3in/3c/FZd3VB8fPf669TNMiTllC4AmFB02fKNUxWYeRC87KwNMiez8VepPJ8oF3TDGuN39bgI8zmoKI6YM5m16HoaQeqiJ3leD/rUULdEiec5br+aidgd0ddP+2wNKaUIK8lzYurlxr8WNWa+nqkWJHGKQYZ2Gt46mOhpCdEzIuvQqQ5vK7JuTO4MJgjsgQJ8a0D9VF45hxOEXZ8KIKB6ZwWZWYpS9v7X+GEivtSIqxIxgMIWdck5DjknUecRCJcKw3eruQ202gaMiGRvVa7+SunoSNRs0dY3/Lq8AHK6usLSfAjvexIFOZVgJXxtMeOZ9APFYYWvDYjMKZHRzXVts+TSYS+xegB3eSsKsQZryV1hGsES1CLzH44VMo0ARL72y61brcuQGVFpT2DpOTS32/MLNBdAgUP1tgtJQ0e6Xt9ba+qR/jkwEnm7EQ3zXalE5fSvL8KqVvb3pq8hnQppMR424m8XYtVXOLn3geVjBtLBClcqmSeFUg6+lB0UoYq1b0DbqLMSe9ez6ZI2iYejQ+FVO3ERDYVkZJlispfKazjqGba0eebscSRHU81reoUUsNee0yw5LEkN10v3IUBGusQhD554QUvbe9lERA8H8eVZjCqvgSVGdsyOvoktafSRNjcgOWRPqXsXyN7seSlQPo5swPu7qQuiAXo=
